### ISSUE TITLE
How to change the number of parallel tasks?

### ISSUE THREAD

**Issue by AmyXS** [marksatt/DistCode#1]
Hi Mark, i assume that there would be a way to change how to change the number of jobs that runs in parallel? At the moment it is set to the number of cores on my machine. Please let me know how it's done.

**Comment by marksatt** [comment]
DistCode currently assumes that there can be 1 task per CPU core (modulo a memory heuristic: see AppDelegate.m) for each machine running DistCode & connected. If the load increases on a machine DistCode may temporarily reduce the number of jobs it can handle. There isn't a way to change this presently.

In order to get parallel compilation from within Xcode you need to select the distcc compiler - unfortunately I haven't updated the build for latest Xcode versions so it won't show-up. You'll need to add the compatibility UUID (DVTPlugInCompatibilityUUID) from Xcode.app/Contents/Info.plist to the distcc plugin's list of UUIDs (DVTPlugInCompatibilityUUIDs) in ~/Library/Application Support/Developer/Shared/Xcode/Plug-Ins/Distcc 3.2xcplugin/Contents/Info.plist. Then restart Xcode & you'll be able to select distcc as a compiler.

**Comment by AmyXS** [comment]
Thanks for getting back to me! Maybe i didn't make it clear enough, I agree that 1 task per CPU for each machine should be the way it work, however, it only creates 4 tasks(number of cores on my machine) at a time, when there are more than 10 cores connected, and show up as hosts. Is there a way to use all cores?
All machines are running Xcode5, so there isn't any problem selecting distcc as the compiler. :)

**Comment by marksatt** [comment]
Run DistCode & get all the hosts in the list, then check what the setting of IDEBuildOperationMaxNumberOfConcurrentCompileTasks is in ~/Library/Preferences/com.apple.dt.Xcode.plist

If this is 4 then for some reason it has decided not to count your other machines in AppDelegate.m's writeDmucsHostsFile method. Xcode should pick up changes to this value automatically & certainly it does for me, however I've only tested in a very limited number of circumstances.

**Comment by AmyXS** [comment]
my ~/Library/Preferences/com.apple.dt.Xcode.plist doesn't have IDEBuildOperationMaxNumberOfConcurrentCompileTasks..I added it in and changed it to 20, but it didn't work for me. might be because that im on Yosemite? but cheers for answering anyway!

**Comment by AmyXS** [comment]
might be real helpful to have a parameter we cud pass in in the GUI that overwrites IDEBuildOperationMaxNumberOfConcurrentCompileTasks?

**Comment by marksatt** [comment]
This may also be related to https://github.com/marksatt/DistCode/issues/5

I'll add an override for how many build tasks each host can execute to the options. In solving Issue #5 I won't have to set this variable anymore, so you would be allowed to set it to override whatever DistCode has decided is the optimum number of parallel compiles. Don't expect this work anytime soon though.

**Comment by AmyXS** [comment]
That will be awesome man!! Thanks a lot!

**Comment by marksatt** [comment]
You can now override the maximum number of tasks on each compile host running DistCode - set Max Jobs. in the options to something greater than 0.

**Comment by AmyXS** [comment]
Thanks Mark!! Very keen to try this out!
