### ISSUE TITLE
Jobs not distributing to other machines

### ISSUE THREAD

**Issue by jtgans** [marksatt/DistCode#5]
By making use of the distcc compiler in Xcode 6, I've been able to at least see the number of jobs popping around, but unfortunately they're all going to the local machine I'm on -- both through localhost and its public IP address. The other machine doesn't actually get any jobs at all.

Any idea what might be going on here?

![screen shot 2015-03-20 at 4 29 57 pm](https://cloud.githubusercontent.com/assets/595205/6762482/70a56790-cf1e-11e4-91b3-43edb3f5fbf7.png)

![screen shot 2015-03-20 at 4 30 09 pm](https://cloud.githubusercontent.com/assets/595205/6762484/76f9c05a-cf1e-11e4-83bd-f5c5c1111e54.png)

**Comment by jtgans** [comment]
After much testing, this seems to be an Xcode 6 parallelization problem. Apparently it refuses to spawn more than 16 tasks, regardless of the plist setting. If I run distcc from the command line through a poor-man's parallel script during an Xcode build, I can push jobs off of the local machine over to another machine.

This problem may actually defeat this whole plugin. :-1:

**Comment by marksatt** [comment]
Darn. Apologies for that, but you are right that is out of my hands. I hadn't been testing with Xcode's build system. My primary test case of DistCode is actually Unreal Engine 4 which has its own build system outside of Xcode. 

It isn't hopeless though - I'm pretty sure I can use my compiler wrapper to issue the compile task, then return immediately. All the collated output could be returned to Xcode at dependent compile tasks (input file is the output file from a previous job) or the link stage. This will take a while to sort out & will be part of the much bigger rewrite to use Icecc instead of the hacked-up version of distcc.

**Comment by marksatt** [comment]
I am reliably informed that this has been fixed by Apple in Xcode 7.
